<?php

use  \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * 
 *  
 */
function deckblog_card_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.deckblog_card':
        return t(
            '<h2>Deck Blog</h2>
            <p>Este es el modulo utilizado para mostrar la carta de manera aleatoria, especificando las variables 
            y mostrando cada uno de los datos que contiene la carta de manera ordenada y especifica</p> <br>
            <p>El modulo cambia el valor de la carta cada vez que se recarga la pagina</p>');
    }
  }